steps:

# pull the image
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - '-c'
    - >-
      docker pull us-central1-docker.pkg.dev/eighth-vehicle-375706/sample-api-nodejs/sample-api-nodejs:latest
      || exit 0

# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'us-central1-docker.pkg.dev/eighth-vehicle-375706/sample-api-nodejs/sample-api-nodejs:$COMMIT_SHA'
    - '-t'
    - 'us-central1-docker.pkg.dev/eighth-vehicle-375706/sample-api-nodejs/sample-api-nodejs:latest'
    - '--cache-from'
    - 'us-central1-docker.pkg.dev/eighth-vehicle-375706/sample-api-nodejs/sample-api-nodejs'
    - '.'
  #id: Build

# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/eighth-vehicle-375706/sample-api-nodejs/sample-api-nodejs:$COMMIT_SHA']

  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'sample-api-nodejs', '--image', 'us-central1-docker.pkg.dev/eighth-vehicle-375706/sample-api-nodejs/sample-api-nodejs', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY